### ISSUE TITLE
Trying to run the project , Getting error in dependencies  

### ISSUE THREAD

**Issue by uplsourav** [mmaheo/tonights-movie-ios#1]
![image](https://user-images.githubusercontent.com/41101565/74811578-ca344d80-5317-11ea-9d8a-5b79dda4846f.png)

**Comment by akinoavx13** [comment]
Hi !

Did you run `carthage update --platform ios` to install project dependencies ?

**Comment by uplsourav** [comment]
![image](https://user-images.githubusercontent.com/41101565/74827100-cf52c600-5332-11ea-8b80-c751aa62649f.png)
Yes, I tried to run this command but it's got failed, trying to resolve the issue, I shared the image with the issue.

**Comment by akinoavx13** [comment]
Ok I tried on my side and that working.
Can you please, copy and paste the output of the error here ?

**Comment by uplsourav** [comment]
souravs-MacBook-Air:netflix-like-ios sourav$ carthage update --platform iOS
*** Fetching Kingfisher

*** Fetching Cache
*** Fetching Alamofire
*** Checking out Cache at "5.2.0"
*** Checking out Kingfisher at "4.10.1"
*** Checking out Alamofire at "4.9.1"
*** xcodebuild output can be found in /var/folders/f1/t797t01n18g3s4mk5f844hnh0000gn/T/carthage-xcodebuild.94VFVk.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Cache-iOS" in Cache.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/sourav/Documents/Project/iosProjects/netflix-like-ios/Carthage/Checkouts/Cache/Cache.xcodeproj -scheme Cache-iOS -configuration Release -derivedDataPath /Users/sourav/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/Cache/5.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/f1/t797t01n18g3s4mk5f844hnh0000gn/T/Cache SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/sourav/Documents/Project/iosProjects/netflix-like-ios/Carthage/Checkouts/Cache)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/f1/t797t01n18g3s4mk5f844hnh0000gn/T/carthage-xcodebuild.94VFVk.log
souravs-MacBook-Air:netflix-like-ios sourav$ 
souravs-MacBook-Air:netflix-like-ios sourav$ carthage update --platform iOS
*** Fetching Alamofire
*** Fetching Kingfisher
*** Fetching Cache
*** Checking out Kingfisher at "4.10.1"
*** Checking out Alamofire at "4.9.1"
*** Checking out Cache at "5.2.0"
*** xcodebuild output can be found in /var/folders/f1/t797t01n18g3s4mk5f844hnh0000gn/T/carthage-xcodebuild.RSgNWk.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Cache-iOS" in Cache.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/sourav/Documents/Project/iosProjects/netflix-like-ios/Carthage/Checkouts/Cache/Cache.xcodeproj -scheme Cache-iOS -configuration Release -derivedDataPath /Users/sourav/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/Cache/5.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/f1/t797t01n18g3s4mk5f844hnh0000gn/T/Cache SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/sourav/Documents/Project/iosProjects/netflix-like-ios/Carthage/Checkouts/Cache)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/f1/t797t01n18g3s4mk5f844hnh0000gn/T/carthage-xcodebuild.RSgNWk.log

**Comment by uplsourav** [comment]
![image](https://user-images.githubusercontent.com/41101565/74827997-57859b00-5334-11ea-9f18-372b38fcf63d.png)

**Comment by akinoavx13** [comment]
Can you try to clear your carthage cache by running :
`rm -rf ~/Library/Caches/org.carthage.CarthageKit`
and then, fetch dependencies again by running :
`carthage update --platform ios`

**Comment by akinoavx13** [comment]
Which Xcode version do you use ?

**Comment by uplsourav** [comment]
Xcode Version 10.2 (10E125)

**Comment by uplsourav** [comment]
souravs-MacBook-Air:netflix-like-ios sourav$ carthage update --platform ios
*** Cloning Kingfisher
*** Cloning Alamofire
*** Cloning Cache
*** Checking out Cache at "5.2.0"
*** Checking out Kingfisher at "4.10.1"
*** Checking out Alamofire at "4.9.1"
*** xcodebuild output can be found in /var/folders/f1/t797t01n18g3s4mk5f844hnh0000gn/T/carthage-xcodebuild.C9gQo5.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Cache-iOS" in Cache.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/sourav/Documents/Project/iosProjects/netflix-like-ios/Carthage/Checkouts/Cache/Cache.xcodeproj -scheme Cache-iOS -configuration Release -derivedDataPath /Users/sourav/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/Cache/5.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/f1/t797t01n18g3s4mk5f844hnh0000gn/T/Cache SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/sourav/Documents/Project/iosProjects/netflix-like-ios/Carthage/Checkouts/Cache)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/f1/t797t01n18g3s4mk5f844hnh0000gn/T/carthage-xcodebuild.C9gQo5.log

**Comment by akinoavx13** [comment]
Indeed, I reproduced the bug on Xcode 10.2 (10E125).
It seems that Xcode10.2 failed to compile hypersolo/Cache ...
```
The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7
(3 failures)
``` 

This issues is fixed on the latest Xcode 11.3.1 (11C505).
Can you update your Xcode to this following version ?

**Comment by uplsourav** [comment]
Okay I'm updating the Xcode version

**Comment by mmaheo** [comment]
Tell me if that solve your issue

**Comment by uplsourav** [comment]
Yes, I've updated the Xcode version, It's running now,
Thank you for your help. I really appreciate the work you did in the
project. I

*Thanks & Regards*
Sourav Das
Chief Mobility Officer
------------------------------
UNDERSCORE TECHNOLOGY PVT. LTD. <https://underscoretec.com/>
M : +91 8945030918 | E : sourav.das@underscoretec.com
L : Find us on map <https://goo.gl/maps/5v69Mp7jiUyvwVNB8>
